# Generated by Django 4.0.1 on 2022-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniProject', '0002_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_file',
            field=models.FileField(upload_to='document_files'),
        ),
    ]
